image:
  file: .gitpod.Dockerfile
 
tasks:
  - command: >
    npm i -g @angular/cli@6.1.2 &&
    ng analytics off &&
    npm i -g typescript@2.7.1 &&
    npm i -g eslint

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4200
    onOpen: open-preview

vscode:
  extensions:
    - esbenp.prettier-vscode
    - vscode-icons-team.vscode-icons
    - dbaeumer.vscode-eslint
    - coenraads.bracket-pair-colorizer
    
