image:
  file: .gitpod.Dockerfile
  
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4200
    onOpen: open-preview

vscode:
  extensions:
    - esbenp.prettier-vscode
    - vscode-icons-team.vscode-icons
    - dbaeumer.vscode-eslint
    - coenraads.bracket-pair-colorizer